version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "changelog_cli"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "changelog_cli"
    schedule:
      interval: "daily"
