name: dart_utiliites
repository: https://github.com/orestesgaolin/dart_utiliites
packages:
  - changelog_cli
command:
  version:
    workspaceChangelog: false
scripts:
  changelog:
    name: changelog
    description: "Generates the changelog using changelog_cli"
    run: changelog_cli generate
