name: dart_utiliites
repository: https://github.com/orestesgaolin/dart_utiliites
packages:
  - changelog_cli
command:
  version:
    workspaceChangelog: false
    includeScopes: false
scripts:
  changelog:
    name: changelog
    description: "Generates the changelog using changelog_cli"
    run: changelog_cli generate > CHANGELOG.md
  version: cd changelog_cli && dart run build_runner build --delete-conflicting-outputs
