name: dart_utiliites
repository: https://github.com/orestesgaolin/dart_utiliites
packages:
  - changelog_cli
command:
  version:
    workspaceChangelog: false
    includeScopes: false
    updateChangelog: false
scripts:
  changelog:
    name: changelog
    description: "Generates the changelog using changelog_cli"
    run: changelog_cli generate --start `git describe --tags --abbrev=0`
  generate:
    name: generate
    run: cd changelog_cli && dart run build_runner build --delete-conflicting-outputs
  preversion:
    name: preversion
    run: melos run generate && melos run changelog
