name: changelog_cli
description: Simple CLI to generate basic changelog for your project using conventional commits
version: 0.3.0
repository: https://github.com/orestesgaolin/dart_utilities/tree/main/changelog_cli
screenshots:
  - description: "Example usage of the changelog_cli"
    path: example/screenshots/changelog_cli.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.5.0
  collection: ^1.17.0
  conventional_commit: ^0.6.0+1
  equatable: ^2.0.5
  file: ^7.0.1
  git: ^2.2.0
  intl: ^0.19.0
  mason_logger: ^0.2.16
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  changelog_cli:
