name: changelog_cli
description: Simple CLI to generate basic changelog for your project using conventional commits
version: 0.6.1
repository: https://github.com/orestesgaolin/dart_utilities/tree/main/changelog_cli
screenshots:
  - description: "Example usage of the changelog_cli"
    path: example/screenshots/changelog_cli.png

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  cli_config: ^0.2.0
  collection: ^1.19.1
  conventional_commit: ^0.6.1+1
  equatable: ^2.0.7
  file: ^7.0.1
  git: ^2.3.1
  intl: ^0.20.2
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.6.0
  build_verify: ^3.1.1
  build_version: ^2.1.2
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

executables:
  changelog_cli:
