name: slack_cli
description: Simple CLI to send Slack messages
version: 0.2.1
repository: https://github.com/orestesgaolin/dart_utilities/tree/main/slack_cli
screenshots:
  - description: "Example usage of the changelog_cli"
    path: example/screenshots/slack_cli_output.png

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  http: ^1.2.2
  mason_logger: ^0.3.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  slack_cli:
