name: Build changelog_cli

on:
  push:
    tags:
      - "changelog_cli-v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_changelog_cli:
    name: Build changelog_cli
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - binary-name: changelog_cli
            os: ubuntu-latest
          - binary-name: changelog_cli.exe
            os: windows-latest
          - binary-name: changelog_cli
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: cd changelog_cli
      - run: dart pub get
      - run: mkdir build
      - run: mkdir build/${{ matrix.os }}
      - run: dart compile exe bin/changelog_cli.dart -o build/${{ matrix.os }}/${{ matrix.binary-name }}
      - uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.os }}
          path: build/${{ matrix.os }}

    release:
      needs: build_changelog_cli
      name: Create GitHub Release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: bin-ubuntu-latest
            path: bin-linux
        - uses: actions/download-artifact@v2
          with:
            name: bin-macos-latest
            path: bin-macos
        - uses: actions/download-artifact@v2
          with:
            name: bin-windows-latest
            path: bin-windows
        - uses: softprops/action-gh-release@v1
          with:
            draft: true
            files: bin-*/*
