name: CI disk_analyzer_cli

on:
  push:
    branches: ["main"]
    paths:
      - "disk_analyzer_cli/**"
      - ".github/workflows/disk_analyzer_cli.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "disk_analyzer_cli/**"
      - ".github/workflows/disk_analyzer_cli.yml"
  workflow_dispatch:

jobs:
  ci:
    defaults:
      run:
        working-directory: disk_analyzer_cli
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Compile CLI
        run: dart build cli --target bin/disk_analyzer_cli.dart --output build