name: CI git_chain

on:
  push:
    branches: ["main"]
    paths:
      - "git_chain/**"
      - ".github/workflows/git_chain.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "git_chain/**"
      - ".github/workflows/git_chain.yml"
  workflow_dispatch:

jobs:
  ci:
    defaults:
      run:
        working-directory: git_chain
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Compile CLI
        run: dart build cli --target bin/git_chain.dart --output build
